app:
  version: ${project.version} # Replaced by Gradle
  security:
    encryptionKeyBase64: # Override in application-local.yml, see local/readme.md
  frontend:
    host: http://localhost:3000
    basePath: /kiri
    cookiesDomain: localhost
  auth:
    telegram:
      callbackUrl: http://localhost:8080/auth/telegram/callback
      botUsername: dev_kirigatewaybot
  backend:
    host: http://localhost:8080
    basePath: /
  integration:
    telegram:
      botId: # Override in application-local.yml, see local/readme.md
      apiKey: # Override in application-local.yml, see local/readme.md
    anthropic:
      apiKey: # Override in application-local.yml, see local/readme.md
    openai:
      apiKey: # Override in application-local.yml, see local/readme.md
    google:
      genAi:
        apiKey: # Override in application-local.yml, see local/readme.md

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kiri
    username: kiri
    password: kiri
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: KiriHikariPool
  config:
    import:
      - "optional:file:./local/application-local.yml"
      - "optional:file:./config/application.yml"
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none # Disabled because of pgvector
    properties:
      hibernate.format_sql: true
      hibernate.type.preferred_json_mapper: jackson

logging:
  level:
    root: INFO
    io:
      ktor: OFF