version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    container_name: kiri-backend
    ports:
      - '8080:8080'

  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    container_name: kiri-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      # Base URL for API requests
      - API_BASE_URL=http://backend:8080/kiri